[package]
name = "julia-cms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.24.0"
strum_macros = "0.24.0"
ipfsapi = "0.2"
futures = "0.3"
codegen = "0.1.3"